name: Github Actions workflow

on:
  push:
    branches:
      - main

jobs:
  check_repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Check errors
        run: npm run linter
      - name: Checking appropriate document formatting
        run: npm run check-format
      - name: Exit command
        run: echo "all went good"
      - name: Running tests
        run: npm run test
