name: Github Actions workflow

on:
  push:
    branches:
      - main

jobs:
  first_step:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hola, estos son mis primeros pasos en gh-actions"

  install_dependencies:
      runs-on: ubuntu-latest
      steps:
        - name: Install Dependencies
          run: npm install

  run_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check errors
        run: npm run linter
  
  format_document:
    runs-on: ubuntu-latest
    steps:
      - name: Format document with prettier
        run: npm run format
  
  say_good_bye:
    runs-on: ubuntu-latest
    steps:
      - name: say good bye
        run: echo "see u later"