name: workflow on pull request

on:
    issue_comment:
      branches:
      - main

jobs:
  first_step:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "esto se ejecuto despues de realizar una pr"