name: workflow on pull request

on:
  pull_request:
    branches: [main]

jobs:
  first_step:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "esto se ejecuto despues de realizar una pr"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Running linter
        run: npm run linter
      - name: Running document format checking
        run: npm run check-format
